files:
  - source: /src/main/resources/assets/touhou_little_maid/lang/en_us.json
    translation: /src/main/resources/assets/touhou_little_maid/lang/%locale%.json
  - source: /docs/*.md
    translation: /docs/%two_letters_code%/%original_file_name%
